config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :suppliers
  resources :reviews
  resources :orders
  resources :customers
  resources :books_orders
  resources :books
  resources :authors
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  devise_for :users
  root to: 'books#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/books_order.rb
class BooksOrder < ApplicationRecord
  belongs_to :book
  belongs_to :order
end

app/controllers/books_orders_controller.rb
class BooksOrdersController < ApplicationController
  before_action :set_books_order, only: %i[ show edit update destroy ]

  # GET /books_orders or /books_orders.json
  def index
    @books_orders = BooksOrder.all
  end

  # GET /books_orders/1 or /books_orders/1.json
  def show
  end

  # GET /books_orders/new
  def new
    @books_order = BooksOrder.new
  end

  # GET /books_orders/1/edit
  def edit
  end

  # POST /books_orders or /books_orders.json
  def create
    @books_order = BooksOrder.new(books_order_params)

    respond_to do |format|
      if @books_order.save
        format.html { redirect_to books_order_url(@books_order), notice: "Books order was successfully created." }
        format.json { render :show, status: :created, location: @books_order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @books_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books_orders/1 or /books_orders/1.json
  def update
    respond_to do |format|
      if @books_order.update(books_order_params)
        format.html { redirect_to books_order_url(@books_order), notice: "Books order was successfully updated." }
        format.json { render :show, status: :ok, location: @books_order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @books_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books_orders/1 or /books_orders/1.json
  def destroy
    @books_order.destroy

    respond_to do |format|
      format.html { redirect_to books_orders_url, notice: "Books order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_books_order
      @books_order = BooksOrder.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def books_order_params
      params.require(:books_order).permit(:book_id, :order_id)
    end
end

app/helpers/books_orders_helper.rb
module BooksOrdersHelper
end

app/views/books_orders/_books_order.html.erb
<div id="<%= dom_id books_order %>">
  <p>
    <strong>Book:</strong>
    <%= books_order.book_id %>
  </p>

  <p>
    <strong>Order:</strong>
    <%= books_order.order_id %>
  </p>

</div>

app/views/books_orders/_form.html.erb
<%= form_with(model: books_order) do |form| %>
<% if books_order.errors.any? %>
<div id="error_explanation" class="bg-red-50 p-6 rounded text-red-800">
  <h2 class="text-lg font-semibold mb-3"><%= pluralize(books_order.errors.count, "error") %> prohibited this books_order from being saved:</h2>

  <ul class="list-disc leading-relaxed">
    <% books_order.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

  <div class="mb-6">
        <%= form.label :book_id, class: label_class %>
          <%= form.text_field :book_id, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :order_id, class: label_class %>
          <%= form.text_field :order_id, class: input_class %>
      </div>

<%= form.submit class: button_class(theme: 'primary') %>

<% if books_order.persisted? %>
<%= link_to "Cancel", books_order, class: "text-neutral-700 underline inline-block ml-3" %>
<% else %>
<%= link_to "Cancel", books_orders_path, class:  "text-neutral-700 underline inline-block ml-3" %>
<% end %>
<% end %>

app/views/books_orders/edit.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between mb-6 flex-wrap">
    <h1 class="font-bold text-3xl mb-6">Edit books_order</h1>
    <% if @books_order.persisted? %>
    <%= button_to 'Destroy', @books_order, method: :delete, class: "text-red-700 underline", data: { turbo_confirm: 'Are you sure?' } %>
    <% end %>
  </div>

  <%= render 'form', books_order: @books_order %>
</div>

app/views/books_orders/index.html.erb
<div class="container mx-auto px-4">
  <div class="flex items-center justify-between flex-wrap mb-6">
    <h1 class="text-3xl font-bold">Books_orders</h1>

    <%= link_to new_books_order_path, class: button_class(theme: "primary") do %>
    Add New Books order
    <% end %>
  </div>

  <table class="table-auto border-collapse border-slate-400 w-full">
    <thead class="bg-slate-50 dark:bg-slate-700">
      <tr>
        
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Book</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Order</th>
                
          <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left"></th>
        
      </tr>
    </thead>

    <tbody>
      <% @books_orders.each do |books_order| %>
      <%= content_tag :tr, id: dom_id(books_order), class: dom_class(books_order) do %>
      

              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= books_order.book %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= books_order.order %></td>
      
      
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= link_to 'Show', books_order %></td>
      
      <% end %>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/books_orders/new.html.erb
<div class="max-w-3xl mx-auto px-4">
  <h1 class="font-bold text-3xl mb-6">New books_order</h1>

  <%= render 'form', books_order: @books_order %>
</div>

app/views/books_orders/show.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between">
    <h1 class="flex-1 font-bold text-3xl">Books_order</h1>

    <div class="flex-wrap lg:flex items-center lg:space-x-3">
      <%= link_to books_orders_path, class: button_class(theme: "transparent") do %>
      All Books_orders
      <% end %>
      <%= link_to edit_books_order_path(@books_order), class: button_class(theme:"primary") do %>
      Edit
      <% end %>
    </div>
  </div>

  <ul class="text-slate-700">
      <li>
        <p class="font-semibold">Book:</p>
        <p><%= @books_order.book %></p>
      </li>
      <li>
        <p class="font-semibold">Order:</p>
        <p><%= @books_order.order %></p>
      </li>
  </ul>
</div>